### ISSUE TITLE
0.6.0 release?

### ISSUE THREAD

**Issue by seibert** [pytroll/donfig#14]
Would it be possible to cut a new release of donfig?  The warning fixed in #10 says that it becomes an error in Python 3.9, which came out a few months ago.

**Comment by djhoese** [comment]
Sure, let me see what I can do. I was going to say maybe a 0.5.1 release, but I guess since we are dropping Python 2 support that is more important and warrants the 0.6 bump.

I'll need to port the CI to github workflows and then make a release. I'll see if I can do this today or tomorrow.

**Comment by djhoese** [comment]
Version 0.6.0 is now out on PyPI. Conda-forge will come later.

**Comment by djhoese** [comment]
conda-forge should be available in a little bit.

**Comment by seibert** [comment]
Thanks so much!
